### PR TITLE
add array type hint to `PhoneNumber::__unserialize`

### LINKED ISSUE #636: Error when testing Symfony code using the `PhoneNumber` class due to mismatched signature for `__unserialize`
Hi,

I'm building an API using Symfony and API-Platform. Since phone number validation is crucial to the business logic, and since libphonenumber-for-php is already used by legacy projects, I'm reusing it for this project via odolbeau/phone-number-bundle.

So far so good on the business logic code, but I'm running into an issue writing tests for code using the `PhoneNumber` class, notably Doctrine entities that have a `PhoneNumber` property.

Testing through an `HttpClientInterface` seems to generate a proxy for `PhoneNumber` that uses the `LazyProxyTrait`, but also extends `PhoneNumber`. This leads to this fatal error : 
```log
Fatal error: Declaration of Symfony\Component\VarExporter\LazyProxyTrait::__unserialize(array $data): void
must be compatible with libphonenumber\PhoneNumber::__unserialize($data)
in /app/vendor/symfony/var-exporter/LazyProxyTrait.php on line 322
```

The source of the error is the missing `array` type-hint on the `$data` argument for the `__unserialize` method.  According to php.net, the expected signature for it is :
```php
public __unserialize(array $data): void
```

Is there a reason for omitting the hint, like keeping backwards compatibility ? Otherwise I have a branch with the fix that I can submit.

### PR DESCRIPTION
**Pull request by IcarusSosie**
fixes #636

### CODE REVIEW

**Comment by IcarusSosie** [comment]
Just ran the tests locally, seems to work fine on php 8.3.7. Should I run them on other versions ?

**Comment by giggsey** [comment]
So apparently this works in PHP 5.3. I had completely forgotten you could use type hints back then.

I'll review closer within a few days, but will likely merge.

Thanks

**Comment by IcarusSosie** [comment]
Oh, just saw your comment on the PR. That's awesome, thanks !

**Comment by giggsey** [comment]
Thanks for the fix.

The next version will be released once Google release their next version (to maintain version number compatibility). That'll likely be within two weeks.

**Pull request merged**
