### PR TITLE
Use giggsey/Locale instead of relying on the intl extension

### PR DESCRIPTION
**Pull request by giggsey**
Remove the dependency on the [intl](http://php.net/intl) extension, and instead use [giggsey/Locale](https://github.com/giggsey/Locale) which has the latest CLDR data.

It's a separate project so that they can be updated independently (CLDR releases seem to happen twice a year, libphonenumber releases about every month).

There have been suggestions in the past to use symfony/intl, but this only provides English data.

References: #43, #45, #46 (18 months later than originally planned).

Todo:
 - [ ] Tidy up giggsey/Locale (README etc.) and tag a stable release
 - [ ] Decide what version this should be introduced in? Should this count as BC breaking?

### CODE REVIEW

**Comment by giggsey** [comment]
@thewilkybarkid, @Propaganistas, @Borales, @saruman: As maintainers of linked integrations, thoughts?

**Comment by Propaganistas** [comment]
I'd highly vote for utilizing an existing top CLDR-compiling package (https://packagist.org/search/?q=iso3166) to prevent the "risk" of redundant data.

E.g. https://github.com/alcohol/iso3166

**Comment by giggsey** [comment]
@Propaganistas Agreed. However, those libraries (I looked at the top two) only have the country names in English.

For example, the country name for 'DE' in English is Germany, but in German is Deutschland.

**Comment by Propaganistas** [comment]
@giggsey How about https://github.com/commerceguys/intl?

**Comment by giggsey** [comment]
https://github.com/commerceguys/intl is PHP 5.4 and up.

I just found https://github.com/punic/punic, which seems to cover what we need. However, it's out of date (there is an open Issue to update, but it's had no activity since the end of April), and it stores the data in JSON files (I'm not keen on the overhead there).

**Comment by Propaganistas** [comment]
Since 5.3 is end-of-life almost 2 years ago, I'd go for a breaking release and use https://github.com/commerceguys/intl

**Comment by giggsey** [comment]
I would love to, but I know of clients that still require this library who are stuck on 5.3.

**Comment by git-webmaster** [comment]
Hi.
Seems like my issue fits this thread, some bug appeared in last release:

In this code:

`
$number = $phoneUtil->parse("+1 646-282-3400", "US");       
$geocoder = \libphonenumber\geocoding\PhoneNumberOfflineGeocoder::getInstance();
$phone_region_local = $geocoder->getDescriptionForNumber($number , "pt_BR");
`
$phone_region_local is always "New York, NY", regardless of given locale ("pt_BR" or any other).
But it must be "Nova Iorque" in pt_BR.

Will you please check this out?

**Comment by giggsey** [comment]
@git-webmaster Can you move this to into a new Issue.

I just tried the demo, and it is indeed giving a different result here and for the parent.

**Comment by giggsey** [comment]
In the absence of a suitable alternative, I'm going to complete this and merge it to tie in with v7.5 that Google released last week (that contained no suitable changes for the PHP version), and ready for the 7.5.1 metadata version.

Once Google move up to v8, I'll reconsider dropping PHP 5.unsupported versions.

**Comment by danizord** [comment]
@giggsey Woops! The removal of `libphonenumber\geocoding\Locale` class is a BC break and broke my app :D Why did not you release it as major?

**Comment by giggsey** [comment]
@danizord It wasn't a change of the public API of libphonenumber. Instead it's an internal class that is meant to only be used by libphonenumber-for-php itself.

**Pull request merged**
