### PR TITLE
upgrade symfony console

### PR DESCRIPTION
**Pull request by jasverix**
We have conflicts with packages requiring console 4

### CODE REVIEW

**Comment by giggsey** [comment]
That's a dev dependency, which means if you are requiring giggsey/libphonenumber-for-php, it has no impact on your project at all.

**Comment by giggsey** [comment]
I'll merge this (thanks), but I don't believe it would have caused you any problems.

**Comment by jasverix** [comment]
We had some conflicts on symfony/console, so I just went through all dependencies using that package. But I see now that your package did not block me, it was some other package. I are right, packages in require-dev does not affect normal usage of the package.

**Comment by giggsey** [comment]
No worries.

[`composer why`](https://getcomposer.org/doc/03-cli.md#depends-why-) should help you with that sort of issue in the future.

**Pull request merged**
