### PR TITLE
Refactored some classes for extending in other libraries

### PR DESCRIPTION
**Pull request by iGusev**
I think that if the classes are not declared as `final`, they must be extensible

### CODE REVIEW

**Comment by giggsey** [comment]
I doubt I'm going to be able to look at this for a week or so, as I'm away on holiday at the moment.

But my initial thoughts are concern. If methods / variables are opened up for other libraries to extend, it could make it harder to keep the library in sync with any changes to the libphonenumber project.

**Comment by iGusev** [comment]
I changed `private` to `protected` and `self::` to `static::`. There is no bc brakes, just improvements.

**Comment by giggsey** [comment]
I'm happy with 6ed0e75 changing `self` to `static`.

It's just changing the private methods to protected that concerns me slightly. The change itself doesn't break any BC, but if other projects then start using inheritance to change those methods, then those methods change, or disappear, does that become a BC breaking change?

**Comment by iGusev** [comment]
This will extend the library to the specific tasks. For example, for me, it would be convenient to use a function `PhoneNumberOfflineGeocoder::getCountryNameForNumber` in my project without forking from main project, via inheritance and wrapping

**Comment by giggsey** [comment]
I started writing some example code to get this exact example. Load the region code for the number, and just use the Locale class in PHP to get the country code for the locale. However, I think it could also be a useful function to be public in actual libphonenumber.

For now, I'm going to accept this Pull Request, thanks.

**Pull request merged**
