### PR TITLE
Don't ship docs with releases

### PR DESCRIPTION
**Pull request by willemstuursma**

### CODE REVIEW

**Comment by giggsey** [comment]
Can you leave METADATA-VERSION, and also add the same list to composer.json (in the archive bit)

**Comment by willemstuursma** [comment]
Thanks @giggsey. Since I've touched `composer.json`, I've also added a validation step in the build.

**Comment by giggsey** [comment]
Thanks @willemstuursma 

I'll merge once the tests pass.

**Comment by willemstuursma** [comment]
> I'll merge once the tests pass.

Wow, those tests take a lot of time! 

It's probably the Xdebug + very old PHP versions. Did you consider dropping support for the unsupported PHP versions 5.3-5.5?

**Comment by giggsey** [comment]
Considered it, but I know of clients that still rely on this library and use PHP 5.x.

At the moment, there is little reason to drop support, as the code functionality will still remain compatible. Maybe v9.

One thing I may do is remove code coverage from the unsupported PHP versions

**Comment by willemstuursma** [comment]
Thanks

**Pull request merged**
