### PR TITLE
Fix mapping file for zh_Hant

### PR DESCRIPTION
**Pull request by wmh**
Fix mapping file for zh_Hant base on upstream's MappingFileProvider class

### CODE REVIEW

**Comment by giggsey** [comment]
Hi @wmh,

Thanks for the pull request. Do you have an issue that this change actually resolves? Can you add a unit test showing that your change is working?

There isn't any code upstream that does the same as this, so I'm a bit wary of merging this without having  an actual bug.

**Comment by wmh** [comment]
How to write a test case correctly? Any meta data need to prepared?

The original implementation is here: https://github.com/googlei18n/libphonenumber/blob/master/java/internal/prefixmapper/src/com/google/i18n/phonenumbers/prefixmapper/MappingFileProvider.java#L48

**Comment by giggsey** [comment]
Ahh, thanks.

If you create a file in [Tests/libphonenumber/Tests/Issues](https://github.com/giggsey/libphonenumber-for-php/tree/master/Tests/libphonenumber/Tests/Issues) (call it Issue106.php), and just check that the output for when looking up the geolocation of a number for the zh region matches what is expected.

E.g. the +82822 prefix is 首尔市 for zh, and 首爾市 for zh_Hant.

**Comment by giggsey** [comment]
Thanks, that's great.

I'll tag a new release once Google do their next release (based on previous activity, it might be around two weeks away).

**Pull request merged**
