### PR TITLE
Add PHP requirement to composer.json

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by giggsey** [comment]
> Composer requires PHP 5.3.2+ to run.

So I think this is a bit redundant.

**Comment by JeroenDeDauw** [comment]
That establishes just one boundary of the range. For all I know this thing only supports 5.5 and up. Bad to require people to look at the CI config to find out the min version.

**Comment by giggsey** [comment]
Good point, but I'd like to think it should be the other way around. Packages which are 5.4 and above should specify the minimum version.

**Comment by giggsey** [comment]
I'm happy to merge though.

Could you also edit the README and put a sentence under Installation saying something like:

> This project is supported with PHP 5.3 up to PHP 7. Currently, HHVM is not supported.

Thanks (on mobile so I can't merge from here)

**Pull request merged**
