### PR TITLE
require mbstring polyfill instead of extension

### PR DESCRIPTION
**Pull request by garak**
See #263

### CODE REVIEW

**Comment by giggsey** [comment]
Are we able to get a Travis install without mbstring?

I think we had similar issues trying to test without the intl extension a few years back.

**Comment by giggsey** [comment]
Can you try it for mbstring.

I want to test that it actually uses the polyfill.

**Comment by garak** [comment]
Yes I meant `phpenv config-rm mbstring.ini` (sorry). I'll try.

**Comment by garak** [comment]
I tried, but it didn't work :disappointed: 
Found an [issue](https://github.com/travis-ci/travis-ci/issues/4701), it looks like it's currently unsupported
Maybe the only way is using Docker in Travis (never tried myself)

**Comment by giggsey** [comment]
I just ran the tests locally without ext-mbstring, and they fail because the polyfill package does provide 'mb_strcut'.

**Comment by garak** [comment]
What's the purpose of using `mb_strcut`? Can't `mb_substr` be enough?

**Comment by giggsey** [comment]
It's used in [Matcher](https://github.com/giggsey/libphonenumber-for-php/blob/8.9.9/src/Matcher.php#L72) to split up the preg_match match groups into multi-byte aware groups (otherwise it'll cut based on bytes, rather than characters).

**Comment by garak** [comment]
I see that, I was just wondering if it's overkilled.

**Comment by giggsey** [comment]
It might be possible to work around it. I might have some time next week to take a deeper look at it.

**Comment by k00ni** [comment]
Hi, what is the status here?

**Comment by giggsey** [comment]
> Hi, what is the status here?

The community is welcome to solve this. mbstring is the recommended approach.

**Comment by giggsey** [comment]
After #383, I'll try to have a look at this, as we'll finally be able to test PHP without the mbstring extension.

**Comment by giggsey** [comment]
Apologies @garak, I screwed up the PR by merging master into it.

I've replaced this with #384. The change does appear to be as simple as mb_strcut to substr. I'll merge it tomorrow/Monday if I can't think of any cases which would cause it to fail.

**Pull request closed without merging**
